/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Aug 5 2024
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

void delay();

sbit b1=P1^0;
sbit b2=P1^1;
sbit b3=P1^2;

sbit in1=P2^0;
sbit in2=P2^1;

void delay()
{
   int i=0;
   TMOD=0x10;
   TH1=0x01;
   TH0=0x01;
   TR1=1;
   TR0=1;
   while(TF1==0 && TF0==0);
   TR1=0;
   TR0=0;
   TF1=0;
   TF0=0;
}
   
void main(void)
 {     
    int i=0;
    
    in1=0;
    in2=0;
    
    b1=1;
    b2=1;
    b3=1;
    
   while (1)
   {
      if(b1==0)//75% duty cycle
      {
	 in1=1;
	 in2=0;
	 delay();
	 delay();
	 delay();
	 in1=0;
	 in2=0;
	 delay();
	 }
     else if(b2==0)//50% duty cycle
     {
	in1=1;
	 in2=0;
	 delay();
	 in1=0;
	 in2=0;
	 delay();
	}
     else if(b3==0)//25% duty cycle
     {  
	 in1=1;
	 in2=0;
	 delay();
	 in1=0;
	 in2=0;
	 delay();
	 delay();
	 delay();
	}
      else
      {
	 in1=0;
	 in2=0;
	 }
    }
 }